apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://oci.trueforge.org/truecharts/jellyseerr
      chart: jellyseerr
      targetRevision: "13.17.2"
      helm:
        valueFiles:
          - $values/helm-apps/jellyseerr/values.yaml
    - repoURL: git@github.com:ANdroxee/Devops-B3.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
