image:
  registry: ghcr.io
  repository: fallenbagel/jellyseerr
  tag: 2.2.3

service:
  type: ClusterIP
  port: 80

config:
  persistence:
    enabled: true
    existingClaim: jellyseerr-config
    size: 5Gi
    accessModes:
      - ReadWriteOnce

ingress:
  enabled: true
  ingressClassName: traefik
  annotations: {}
  hosts:
    - host: jellyseerr.cedevapp.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

probes:
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

extraEnv:
  - name: TZ
    value: Europe/Paris
  - name: LOG_LEVEL
    value: info
