image:
  repository: oci.trueforge.org/containerforge/jellyseerr
  tag: "2.7.3"

service:
  main:
    ports:
      main:
        port: 5055

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_LEVEL: info
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

persistence:
  config:
    enabled: true

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: jellyseerr.cedevapp.com
        paths:
          - path: /
            pathType: Prefix
    integrations:
      traefik:
        enabled: true
        entrypoints:
          - web
        forceTLS: false
