image:
  repository: oci.trueforge.org/containerforge/jellyseerr
  tag: "2.7.3"

service:
  main:
    ports:
      main:
        port: 5055

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_LEVEL: info
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi

persistence:
  config:
    enabled: true

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: jellyseerr.cedevapp.com
        paths:
          - path: /
            pathType: Prefix
    integrations:
      traefik:
        enabled: true
        entrypoints:
          - web
        forceTLS: false
