apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellystat
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://oci.trueforge.org/truecharts/jellystat
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/helm-apps/jellystat/values.yaml
    - repoURL: git@github.com:ANdroxee/Devops-B3.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
