image:
  repository: docker.io/cyfershepard/jellystat
  tag: latest

cnpg:
  main:
    enabled: false

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            TZ: Europe/Paris
            POSTGRES_USER: jellystat
            POSTGRES_PASSWORD:
              secretKeyRef:
                name: jellystat-secrets
                key: POSTGRES_PASSWORD
            POSTGRES_IP: jellystat-postgres
            POSTGRES_PORT: "5432"
            JWT_SECRET:
              secretKeyRef:
                name: jellystat-secrets
                key: JWT_SECRET
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

persistence:
  backup:
    enabled: true
    mountPath: "/app/backend/backup-data"

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: jellystat.cedevapp.com
        paths:
          - path: /
            pathType: Prefix
    integrations:
      traefik:
        enabled: true
        entrypoints:
          - web
        forceTLS: false
