image:
  repository: docker.io/cyfershepard/jellystat
  tag: latest

cnpg:
  main:
    enabled: true
    user: jellystat
    database: jellystat

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            TZ: Europe/Paris
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

persistence:
  backup:
    enabled: true
    mountPath: "/app/backend/backup-data"

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: jellystat.cedevapp.com
        paths:
          - path: /
            pathType: Prefix
    integrations:
      traefik:
        enabled: true
        entrypoints:
          - web
        forceTLS: false
