apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ANdroxee/Devops-B3.git
    targetRevision: HEAD
    path: helm-apps/jellyseerr
    directory:
      recurse: true
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true