apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellystat-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: oci://registry-1.docker.io/bitnamicharts/postgresql
      chart: postgresql
      targetRevision: "18.5.8"
      helm:
        valueFiles:
          - $values/helm-apps/jellystat-postgres/values.yaml
    - repoURL: git@github.com:ANdroxee/Devops-B3.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: jellystat-postgres
      namespace: jellyfin
      jsonPointers:
        - /data/password
        - /data/postgres-password
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
