[all]
master ansible_host=10.111.63.101 ansible_user=root ansible_password=
worker ansible_host=10.111.63.102 ansible_user=root ansible_password=
worker2 ansible_host=10.111.63.103 ansible_user=root ansible_password=

[masters]
master

[workers]
worker
worker2
